apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: academind/kub-data-demo:2
          env:
            - name: STORY_FOLDER
              # 1. Empty Dir, 2. Host Path
              # value: 'story'
              valueFrom: 
                configMapKeyRef:
                  name: data-store-env
                  key: folder
          volumeMounts:
            - mountPath: /app/story
              name: story-volume

          # 1. Empty Dir, 2. Host Path
          #volumeMounts:
          #  - mountPath: /app/story
          #    name: story-volume
      volumes:
        - name: story-volume
          persistentVolumeClaim:
            claimName: host-pvc
          
          # 1. Empty Dir 
          # emptyDir: {}
          
          # 2. Host Path
          #hostPath:
          #  path: /data
          #  type: DirectoryOrCreate