apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem # or Block
  storageClassName: standard
  accessModes:
    - ReadWriteOnce # Multiple Pods Single Node
    #- ReadOnlyMany # Multiple Pods Multiple Nodes
    #- ReadWriteMany # Multiple Pods Multiple Nodes
  hostPath:
    path: /data
    type: DirectoryOrCreate